// includes all AST headers

#ifndef AST_H
#define AST_H

#include "ast/Block.h"
#include "ast/Command.h"
#include "ast/Expression.h"
#include "ast/Addition.h"
#include "ast/Multiplication.h"
#include "ast/Division.h"
#include "ast/Subtraction.h"
#include "ast/Equal.h"
#include "ast/Less.h"
#include "ast/Greater.h"
#include "ast/GreaterOrEqual.h"
#include "ast/LessOrEqual.h"
#include "ast/NotEqual.h"
#include "ast/Equal.h"
#include "ast/And.h"
#include "ast/Or.h"
#include "ast/Not.h"
#include "ast/ExpressionNum.h"
#include "ast/ExpressionName.h"
#include "ast/For.h"
#include "ast/If.h"
#include "ast/IntArrayDef.h"
#include "ast/Node.h"
#include "ast/Program.h"
#include "ast/Return.h"
#include "ast/Type.h"
#include "ast/VariableDef.h"
#include "ast/While.h"
#include "ast/FunctionDef.h"
#include "ast/FunctionCall.h"
#include "ast/Assignment.h"
#include "ast/IndirectionAssignment.h"
#include "ast/Indirection.h"
#include "ast/ArraySubscript.h"

#endif
